import torch, random, os
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

from mnist_dataset import MnistDataset
from mylib import load_data

# ------------ 超参数 ------------
BATCH_SIZE  = 256
EPOCHS      = 1
Z_DIM       = 32               # 隐向量维度
LR          = 1e-3
DEVICE      = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ------------ 数据 ------------
transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Lambda(lambda x: x.view(-1))])  # 784 维向量
train_set=MnistDataset()
train_loader = torch.utils.data.DataLoader(dataset=train_set, batch_size=BATCH_SIZE, shuffle=True)

# ------------ 网络 ------------
class AutoEncoder(nn.Module):
    def __init__(self, z_dim=32):
        super().__init__()
        # 编码器 784 -> 128 -> 64 -> z_dim
        self.encoder = nn.Sequential(
            nn.Linear(784, 128), nn.ReLU(),
            nn.Linear(128, 64),  nn.ReLU(),
            nn.Linear(64, z_dim)
        )
        # 解码器 z_dim -> 64 -> 128 -> 784
        self.decoder = nn.Sequential(
            nn.Linear(z_dim, 64),  nn.ReLU(),
            nn.Linear(64, 128),    nn.ReLU(),
            nn.Linear(128, 784),   nn.Sigmoid()  # 像素值归一化到 [0,1]
        )

        try:
            # Check if encoder and decoder weights files exist in current directory
            encoder_path = "AE_encoder.pth"
            decoder_path = "AE_decoder.pth"
    
            if os.path.exists(encoder_path):
                checkpoint = torch.load(encoder_path, map_location=DEVICE)
                self.encoder.load_state_dict(checkpoint)
                print("AutoEncoder: Loaded pre-trained encoder weights")
            else:
                print("AutoEncoder: No pre-trained encoder weights found, initializing randomly")
        
            if os.path.exists(decoder_path):
                checkpoint = torch.load(decoder_path, map_location=DEVICE)
                self.decoder.load_state_dict(checkpoint)
                print("AutoEncoder: Loaded pre-trained decoder weights")
            else:
                print("AutoEncoder: No pre-trained decoder weights found, initializing randomly")
        
        except Exception as e:
            print(f"AutoEncoder: Could not load pre-trained weights: {e}")
    def forward(self, x):
        z = self.encoder(x)
        return self.decoder(z)

net = AutoEncoder(Z_DIM).to(DEVICE)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=LR)

# ------------ 训练 ------------
for epoch in range(1, EPOCHS+1):
    total_loss = 0
    for _,x, _ in train_loader:
        x = x.to(DEVICE)
        optimizer.zero_grad()
        x_hat = net(x)
        loss = criterion(x_hat, x)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch}/{EPOCHS}  MSE={total_loss/len(train_loader):.4f}")

# 保存解码器（我们待会要用它做生成）
torch.save(net.encoder.state_dict(), "AE_encoder.pth")
torch.save(net.decoder.state_dict(), "AE_decoder.pth")
print("Encoder saved to AE_encoder.pth")
print("Decoder saved to AE_decoder.pth")

# ------------ 生成阶段 ------------
decoder = AutoEncoder(Z_DIM).decoder          # 新建一个解码器结构
decoder.load_state_dict(torch.load("AE_decoder.pth", map_location=DEVICE))
decoder.to(DEVICE).eval()

n_gen = 10

fig, axes = plt.subplots(2, 5)
axes = axes.flatten()
with torch.no_grad():
    for i in range(n_gen):
        z = torch.randn(n_gen, Z_DIM).to(DEVICE)  # 随机噪声
        fake_imgs=decoder(z).view(-1, 28, 28).cpu()
        axes[i].imshow(fake_imgs[i], cmap='gray')
        axes[i].set_title(f'{i}', fontsize=10)
        axes[i].axis('off')
plt.suptitle("MNIST digits generated by AE decoder")
plt.tight_layout()
plt.show()