import torch, random, os
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

from mnist_dataset import MnistDataset
from mylib import load_data,interpolate_vectors

# ------------ 超参数 ------------
EPOCHS      = 10
BATCH_SIZE  = 128
Z_DIM       = 32               # 隐向量维度
LR          = 1e-3
DEVICE      = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ------------ 数据 ------------
transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Lambda(lambda x: x.view(-1))])  # 784 维向量
train_set=MnistDataset()
train_loader = torch.utils.data.DataLoader(dataset=train_set, batch_size=BATCH_SIZE, shuffle=True)

# ------------ 网络 ------------
class AutoEncoder(nn.Module):
    def __init__(self, z_dim=32):
        super().__init__()
        # 编码器 784 -> 128 -> 64 -> z_dim
        self.encoder = nn.Sequential(
            nn.Linear(784, 256), 
            nn.ReLU(),
            nn.Linear(256, 128),  
            nn.ReLU(),
            nn.Linear(128, z_dim),
            nn.Sigmoid(),  # 像素值归一化到 [0,1]
        )
        # 解码器 z_dim -> 64 -> 128 -> 784
        self.decoder = nn.Sequential(
            nn.Linear(z_dim, 128),  
            nn.ReLU(),
            nn.Linear(128,256),    
            nn.ReLU(),
            nn.Linear(256, 784),   
        )
        self.optimizer = torch.optim.Adam(self.parameters(), lr=LR)
        self.criterion = nn.MSELoss()
        self.z_dim = z_dim

        try:
            # Check if encoder and decoder weights files exist in current directory
            encoder_path = "AE_encoder.pth"
            decoder_path = "AE_decoder.pth"
    
            if os.path.exists(encoder_path) and os.path.exists(decoder_path):
                checkpoint = torch.load(encoder_path, map_location=DEVICE)
                self.encoder.load_state_dict(checkpoint)
                print("AutoEncoder: Loaded pre-trained encoder weights")
                checkpoint = torch.load(decoder_path, map_location=DEVICE)
                self.decoder.load_state_dict(checkpoint)
                print("AutoEncoder: Loaded pre-trained decoder weights")
            else:
                print("No pre-trained weights found, initializing randomly")
                self._initialize_weights()
        except Exception as e:
            print(f"AutoEncoder: Could not load pre-trained weights: {e}")
    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                nn.init.constant_(m.bias, 0)
    def forward(self, x):
        z = self.encoder(x)
        return self.decoder(z)


    def train_model(self):
        for epoch in range(1, EPOCHS+1):
            total_loss = 0
            for lable,x, lable_tensor in train_loader:
                x = x.to(DEVICE)

                self.optimizer.zero_grad()
                x_hat = self(x)
                loss = self.criterion(x_hat, x)
                loss.backward()
                self.optimizer.step()
                total_loss += loss.item()
            print(f"Epoch {epoch}/{EPOCHS}  MSE={total_loss/len(train_loader):.4f}")

        # 保存解码器（我们待会要用它做生成）
        torch.save(self.encoder.state_dict(), "AE_encoder.pth")
        torch.save(self.decoder.state_dict(), "AE_decoder.pth")
        print("Encoder saved to AE_encoder.pth")
        print("Decoder saved to AE_decoder.pth")

    def show_result(self):
        n_gen = 10

        fig, axes = plt.subplots(2, 5)
        axes = axes.flatten()
        with torch.no_grad():
            for i in range(n_gen):
                z = torch.randn(1, Z_DIM).to(DEVICE)  # 随机噪声
                fake_imgs=self.decoder(z).view(-1, 28, 28).cpu()
                axes[i].imshow(fake_imgs[0], cmap='gray')
                axes[i].axis('off')
                
            plt.suptitle("MNIST digits generated by AE decoder")
            plt.tight_layout()
            plt.show()
    def show_d2d(self):
        # 显示不同z对生成结果的影响
        n_gen = 10
        dataset = MnistDataset()

        fig, axes = plt.subplots(9,10, figsize=(10, 10))
        axes = axes.flatten()
        used=[]
        for d in range(9):
            lable,tl=torch.randint(0,9,(1,)).item(),torch.randint(0,9,(1,)).item()
            while lable == tl:
                tl=torch.randint(0,9,(1,)).item()
            while (lable,tl) in used or (tl,lable) in used:
                lable,tl=torch.randint(0,9,(1,)).item(),torch.randint(0,9,(1,)).item()
            used.append((lable,tl))
            lable,img,_ = dataset.get_digtal_sample(lable) 
            tl,timg,_ = dataset.get_digtal_sample(tl) 
            z1 = self.encoder(img.to(DEVICE)).view(-1, Z_DIM)  
            z2= self.encoder(timg.to(DEVICE)).view(-1, Z_DIM)  
            with torch.no_grad():
                for idx,t in enumerate(interpolate_vectors(z1, z2, n_gen)):
                    fake_imgs=self.decoder(t).view(-1, 28, 28).cpu()
                    axes[d*10 +idx].imshow(fake_imgs[0], cmap='gray')
                    axes[d*10 +idx].axis('off')
        pairs_text = " ".join([f"{f}-{t}" for f, t in used])
        plt.suptitle(f"{pairs_text}")
        plt.tight_layout()
        plt.show()
        
@torch.no_grad()
def sanity_check(model):
    z = torch.randn(1, Z_DIM, device=DEVICE)
    imgs = []
    for digit in range(10):
        y = nn.functional.one_hot(torch.tensor(digit).view(1), 10).float().to(DEVICE)
        x_hat = model.decoder(torch.cat([z, y], 1)).view(28, 28)
        imgs.append(x_hat.cpu())
    # 像素级方差
    stack = torch.stack(imgs)          # 10×28×28
    var = stack.std(dim=0).mean()
    print(f"同一z，不同标签 → 像素标准差={var:.4f}")
    if var < 0.05:
        print("❌ 标签被完全忽略！")
    else:
        print("✅ 标签确实在起作用")

if __name__ == "__main__":
    net = AutoEncoder(z_dim=Z_DIM).to(DEVICE)
    #net.train_model()
    #net.show_result()
    #sanity_check(net)
    net.show_d2d()