import torch, random, os
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

from mnist_dataset import MnistDataset
from mylib import load_data

BATCH_SIZE  = 256
LR          = 1e-3
DEVICE      = torch.device("cuda" if torch.cuda.is_available() else "cpu")
EPOCHS      = 10

MODEL_FILENAME = "mlp_generator.pth"

class Generator(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = nn.Sequential(
            nn.Linear(10+1, 128),
            nn.ReLU(),
            nn.Linear(128, 256),
            nn.ReLU(),
            nn.Linear(256, 784),
            nn.Sigmoid()
        )
        self.loss_function = nn.MSELoss()
        self.optimizer = torch.optim.Adam(self.parameters(), lr=LR)
        
        if os.path.exists(MODEL_FILENAME):
            self.load_state_dict(torch.load(MODEL_FILENAME, map_location=DEVICE))
            print("Loaded generator weights.")
        else:
            print("No previously trained generator found")
    def forward(self, seed,label_onehot):
        input= torch.cat((seed, label_onehot), dim=1)
        return self.fc(input)
    
    def train_model(self):
        train_set=MnistDataset()
        train_loader = torch.utils.data.DataLoader(dataset=train_set, batch_size=BATCH_SIZE, shuffle=True)

        for epoch in range(1, EPOCHS+1):
            total_loss = 0
            for _, x, label in train_loader:
                x = x.to(DEVICE)
                label = label.to(DEVICE)

                self.zero_grad()
                seed = torch.randn(label.size(0),1, device=DEVICE)
                x_hat = self.forward(seed,label)
                loss =self.loss_function(x_hat, x)
                loss.backward()
                self.optimizer.step()
                total_loss += loss.item()
            print(f"Epoch {epoch}/{EPOCHS}  MSE={total_loss/len(train_loader):.4f}")
        torch.save(self.state_dict(), MODEL_FILENAME)
        print("Generator saved to", MODEL_FILENAME)
        self.show_result()

    def gen_one(self,digit):
        self.eval()
        with torch.no_grad():
            label = torch.zeros(1, 10, device=DEVICE)
            label[0, digit] = 1
            seed = torch.randn(label.size(0), 1, device=DEVICE)
            img = self(seed,label).view(28, 28).cpu()
            return img,seed.mean().item()
    def show_result(self):
        fig, axes = plt.subplots(5, 10)
        fig.suptitle("Digits generated by conditional Generator", fontsize=16)
        
        # 对于每个数字(0-9)
        for i in range(5):
            # 生成8个该数字的样本
            for j in range(10):
                # 使用gen_one生成图像
                img,seed = self.gen_one(j)
                
                # 显示在对应的位置
                axes[i, j].imshow(img, cmap='gray')
                axes[i, j].axis('off')
                axes[i, j].set_title(f'{j}/{seed:.3f}', fontsize=10)

        
        plt.tight_layout()
        plt.show()

    def test_model_variance(self):
        countlist=torch.zeros(10)
        for i in range(10):
            digitals=[]
            for j in range(2):
                img,_=self.gen_one(i)
                digitals.append(img.view(-1,784).numpy())
            for k in range(len(digitals)-1):
                duplicate_count = 0
                for m in range(k+1, len(digitals)):
                    if digitals[k].all() == digitals[m].all():
                        duplicate_count += 1
                if duplicate_count > 0:
                    countlist[i] += duplicate_count
        print(countlist)
        plt.bar(range(10), countlist.numpy())
        plt.xlabel("Digit")
        plt.ylabel("Duplicate Count in 10,00 Samples") 
        plt.show()
if __name__ == "__main__":
    pass
    g=Generator()
    g.train_model()
    